config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'restaurants/index'
  get 'restaurants/create'
  get 'restaurants/new'
  get 'restaurants/edit'
  get 'restaurants/show'
  get 'restaurants/update'
  get 'restaurants/destroy'
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion:["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true,numericality: { only_integer: true }, inclusion: (0..5).to_a
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end

  end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def show; end

  def update
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    @restaurant.delete
    redirect_to restaurants_index_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :category, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Restaurants#edit</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurant List</h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li>
        <%= link_to restaurant do %>
          <%= restaurant.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <h2><%= link_to "New Restaurant", restaurants_new_path %></h2>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <h2><%= @restaurant.address %></h2>
  <h2><%= @restaurant.phone_number %></h2>
  <h2><%= @restaurant.category %></h2>

  <h3><%= link_to "Restaurant Index", restaurants_index_path %></h3>
  <h3><%= link_to "Edit", edit_restaurant_path %></h3>
  <h3><%= link_to "Delete",
    @restaurant,
    method: :delete,
    data: { confirm: 'Are you sure?'}  %></h3>

  <h3><%= link_to "Leave comment", new_restaurant_review_path(@restaurant) %></h3>

  <h3>Reviews</h3>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.content %>
        <%= review.rating %>
      </li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New Review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit" %>
  <% end %>
</div>